parameters:
- name: image
  default: ''

jobs:
  - job: 'documentation'
    displayName: 'Documentation'
    pool:
      vmImage: ${{ parameters.image }}
    variables:
      packages_dir: '$(Build.StagingDirectory)/packages'
      docs_build_dir: '$(Build.StagingDirectory)/docs_build'
    steps:
      - bash: |
          set -ex
          mkdir -p "$(packages_dir)"
          mkdir -p "$(docs_build_dir)"
        displayName: 'Make directories'
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          specificBuildWithTriggering: true
          downloadType: 'single'
          artifactName: 'linux-64'
          downloadPath: '$(packages_dir)'
        displayName: 'Download previously build Conda package'
      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add Conda to PATH
      - bash: |
          conda env create -f scipp-developer.yml
        displayName: 'Create Conda environment'
      - bash: |
          set -ex
          source activate scipp-developer
          conda install "$(packages_dir)/linux-64/"scipp-*-py37_*.tar.bz2
        displayName: 'Install Scipp package'
      - bash: |
          set -ex
          cd docs
          source activate scipp-developer
          # Build documentation, redirecting doctrees to avoid size bloat in build documentation
          sphinx-build -d "$(mktemp -d)" . "$(docs_build_dir)"
          # Remove Juptyer notebooks used for documentation build, they are not accessible and create size bloat
          find "$(docs_build_dir)" -type f -name *.ipynb -delete
        displayName: 'Build documentation'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(docs_build_dir)'
          ArtifactName: 'documentation'
        displayName: 'Publish documentation artifacts'
