parameters:
- name: image
  default: ''
- name: conda_package_root
  type: string
  default: ''
- name: py_version
  type: string
  default: ''

stages:
  - stage: 'documentation'
    displayName: 'Documentation'

    jobs:
      - job: 'documentation_build'
        displayName: 'Documentation build'
        pool:
          vmImage: ${{ parameters.image }}
        variables:
          packages_dir: '$(Build.StagingDirectory)/packages'
          docs_build_dir: '$(Build.StagingDirectory)/docs_build'
          package_name: ${{ parameters.conda_package_root }}-py${{ parameters.py_version }}
        steps:
          - bash: |
              set -ex
              mkdir -p "$(packages_dir)"
              mkdir -p "$(docs_build_dir)"
            displayName: 'Make directories'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              specificBuildWithTriggering: true
              downloadType: 'single'
              artifactName: '$(package_name)'
              downloadPath: '$(packages_dir)'
            displayName: 'Download previously built Conda package'
          - bash: |
              echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add Conda to PATH
          - bash: |
              set -ex
              # Specify python version in env file
              sed 's/- python$/- python=${{ parameters.py_version }}/g' scipp-developer.yml > temp-env.yml
              conda env create -f temp-env.yml
            displayName: 'Create Conda environment'
          - bash: |
              set -ex
              source activate scipp-developer
              conda install "$(packages_dir)/$(package_name)/"scipp-*.tar.bz2
            displayName: 'Install Scipp package'
          - bash: |
              set -ex
              cd docs
              source activate scipp-developer
              # Build documentation, redirecting doctrees to avoid size bloat in build documentation
              sphinx-build -d "$(mktemp -d)" . "$(docs_build_dir)"
              # Remove Juptyer notebooks used for documentation build, they are not accessible and create size bloat
              find "$(docs_build_dir)" -type f -name *.ipynb -delete
            displayName: 'Build documentation'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(docs_build_dir)'
              ArtifactName: 'documentation'
            displayName: 'Publish documentation artifacts'
