parameters:
- name: 'py_versions'
  type: object
  default:
    linux: ['3.7']
    osx: ['3.7']
    windows: ['3.7']
- name: 'settings'
  type: object
  default:
    linux:
      image: 'ubuntu-20.04'
      conda_package_root: 'linux-64'
      params:
        ccache: true
    osx:
      image: 'macOS-10.14'
      conda_package_root: 'osx-64'
      params:
        OSX_VERSION: '10.15'
    windows:
      image: 'windows-latest'
      conda_package_root: 'win-64'
- name: 'deploy'
  type: boolean
  default: false
- name: release
  type: boolean
  default: false
- name: conda_label
  type: string
  default: 'test'
- name: verbose
  type: boolean
  default: false

stages:
  - template: code_quality_checks.yml
    parameters:
      image: ${{ parameters.settings.linux.image }}

  - stage: 'build_and_test'
    displayName: 'Build and Test'
    jobs:
      - ${{ each os in parameters.py_versions }}:
        - ${{ each py in os.Value }}:
          - template: build.yml
            parameters:
              verbose: ${{ parameters.verbose }}
              py_version: ${{ py }}
              image: ${{ parameters.settings[os.Key].image }}
              conda_package_root: ${{ parameters.settings[os.Key].conda_package_root }}
              ${{ each param in parameters.settings[os.Key].params }}:
                ${{ param.Key }}: ${{ param.Value }}

  - template: documentation.yml
    parameters:
      image: ${{ parameters.settings.linux.image }}
      conda_package_root: ${{ parameters.settings.linux.conda_package_root }}
      py_version: '3.7'

  - ${{ if eq(parameters.deploy, true) }}:
    - template: deploy.yml
      parameters:
        image: ${{ parameters.settings.linux.image }}
        release: ${{ parameters.release }}
        conda_label: ${{ parameters.conda_label }}
        package_list:
          ${{ each os in parameters.py_versions }}:
            ${{ each py in os.Value }}:
              ${{ parameters.settings[os.Key].conda_package_root }}-py${{ py }}: true
