trigger:
  branches:
    exclude:
      - "*"

pr:
  autoCancel: true
  branches:
    include:
      - master

stages:
  - template: templates/code_quality_checks.yml

  - stage: 'build_and_test'
    displayName: 'Conda Package Build and Unit Tests'

    jobs:
      - job: 'linux'
        displayName: 'Linux'
        timeoutInMinutes: 60
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - checkout: self
            submodules: true
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add Conda to PATH
          - bash: |
              set -ex
              conda --version
              conda install --yes conda-build
            displayName: 'Conda configuration'
          - bash: |
              conda build -c conda-forge ./conda
            displayName: 'Package build'

      - job: 'mac'
        displayName: 'Mac OS'
        timeoutInMinutes: 80
        pool:
          vmImage: 'macOS-10.14'
        steps:
          - checkout: self
            submodules: true
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add Conda to PATH
          - bash: sudo chown -R $USER $CONDA
            displayName: Take ownership of Conda installation
          - bash: |
              set -ex
              conda --version
              conda install --yes conda-build
            displayName: 'Conda configuration'
          - bash: |
              OSX_VERSION=10.15 conda build -c conda-forge ./conda
            displayName: 'Package build'

      - job: 'windows'
        displayName: 'Windows'
        timeoutInMinutes: 60
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: self
            submodules: true
          - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
            displayName: Add Conda to PATH
          - script: |
              conda --version
              conda install --yes conda-build
            displayName: 'Conda configuration'
          - script: |
              conda build -c conda-forge ./conda
            displayName: 'Package build'
